# This will probably require more setup than just running this docker file. Particularly with reverse proxying (I use nginx), it can be a bit of a pain to make work just right. 

version: "3.7"

services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Phoenix
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 8077:80
      - 9443:443
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: linuxserver/mariadb:latest
    container_name: nextcloud_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=#a random string of letters and numbers
      - TZ=America/Phoenix
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=#a random string of letters and numbers
    volumes:
      - ./config_db:/config
    restart: unless-stopped
